### ISSUE TITLE
Search changes

### ISSUE THREAD

**Issue by sqljim** [animalaidunlimited/apoms#158]
We need to alter the search so that:

1: When the first character is an alpha character then we search by tag
2: When the first character is a number and the number is **not** 10 digits long we search by emergency number
3: When the first character is a number and the number is 10 digits long we search by caller number
4: When the search has a \ in it we search by call date (date format dd/mm/yyyy)
5: When the string is not a date, or a tag number, or an emergency number we search by address

6: Tidy up the + and - signs so that they match the + and bin icons to be consistent with the rest of the app.

7: When adding elements to the seach, the search field should reflect the type of search, for instance when selecting date, the search input should change to a date input.

8: When searching by a dropdown, like call outcome, we should include a dropdown with the values in it.

We should clarify before doing this work that we don't just need to do tag number or emergency number search.

**Comment by ankitsingh101** [comment]
When we do search by date they're are three options related to date Call Date, Release Date, Died Date. Currently Default Search is set to Call Date when User do date search
